printWidth: 80 # 代码宽度建议不超过100字符
tabWidth: 2 # tab缩进2个空格
useTabs: true #使用tab缩进，默认false
semi: true # 末尾分号
singleQuote: true # 单引号
jsxSingleQuote: true # jsx中使用单引号
trailingComma: 'es5' # 尾随逗号
arrowParens: 'avoid' # 箭头函数仅在必要时使用()
htmlWhitespaceSensitivity: 'css' # html空格敏感度
vueIndentScriptAndStyle: false